export const GET_REPOSITORY_LIST = 'GET_REPOSITORY_LIST';
export const GET_CONTIBUTOR_LIST = 'GET_CONTIBUTOR_LIST';
export const ADD_TO_FAVARITIES = 'ADD_TO_FAVARITIES';
export const REMOVE_FROM_FAVARITIES = 'REMOVE_FROM_FAVARITIES';